version: "3.9"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: bill-payment-assistant
    ports:
      - ${APP_PORT}:${APP_PORT}
    volumes:
      - .:/app
    depends_on:
      - postgres-db
  postgres-db:
    image: postgres:15-alpine
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
